SourianaMarket/ViewModels/BillItemViewModel.cs
using SourianaMarket.Main.Dto.BillItemDTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SourianaMarket.ViewModels
{
    public class BillItemViewModel
    {
        public IEnumerable<BillItemDto> BillItemDto { get; set; }
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int BillId { get; set; }
        public int UserId { get; set; }
        public int Quantity { get; set; }
        public int OldPrice { get; set; }
        public DateTime Date { get; set; }
        public string ItemName { get; set; }

        public int ItemPrice { get; set; }
        public string ItemImageUrl { get; set; }

        public int Categid { get; set; }
    }
}

SourianaMarket/Controllers/BillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SourianaMarket.Main.Data.Repositories;
using SourianaMarket.Main.Dto.BillDTO;
using SourianaMarket.Main.IData.Interfaces;
using SourianaMarket.Models.Commerce;
using SourianaMarket.Security;
using SourianaMarket.SharedKarnel.Enums;
using SourianaMarket.Util;
using SourianaMarket.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SourianaMarket.Controllers
{
    public class BillController : Controller
    {
        public IBillInterface BillInterface { get; set; }
        public IAccountRepository AccountRepository { get; set; }
        public BillController(IBillInterface billInterface, IAccountRepository accountRepository)
        {
            BillInterface = billInterface;
            AccountRepository = accountRepository;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            var userid = AccountRepository.GetUserId();
            var vm = new BillViewModel()
            {
                BillDto = BillInterface.GetAll(userid),
                IsAdmin = this.User.IsInRole(RoleName.Admin.ToString())
            };
            return View(vm);
        }
        public IActionResult Details()
        {
            var vm = new BillViewModel()
            {
                BillDto = BillInterface.GetAllitem()

            };
            return View(vm);
        }

        private BillViewModel FillViewModel(BillViewModel model)
        {

            return new BillViewModel()
            {
                BillId = model.BillId,
                Date = model.Date

                //ImageUrl = model.ImageUrl
            };

        }
        [HttpPost]
        public IActionResult SaveBillItemInfo(BillViewModel model)
        {

            if (!ModelState.IsValid)
            {
                var viewModel = FillViewModel(model);
                ViewBag.error = "Data incorrect";
                return RedirectToAction(nameof(CartController.Index), nameof(CartController).GetActionName());
            }


            var result = BillInterface.SetBill(new BillDto()
            {
            });
            if (result.ResultType == OperationResultTypes.Success)
            {
                //return json(result);
                return RedirectToAction(nameof(CartController.Index),
                    nameof(CartController).GetActionName());
            }
            ModelState.AddModelError("", "failed to update date");
            //var vm = FillViewModel(model);
            return RedirectToAction(nameof(CartController.Index),
                       nameof(CartController).GetActionName());
        }


        [Authorize]
        public IActionResult CheckOut()
        {

            var result = BillInterface.Checkout(AccountRepository.GetUserId());
            if (result)
            {
                //return json(result);
                return RedirectToAction(nameof(BillController.Index),
                    nameof(BillController).GetActionName());
            }
            ModelState.AddModelError("", "failed to update date");
            //var vm = FillViewModel(model);
            return RedirectToAction(nameof(CartController.Index),
                       nameof(CartController).GetActionName());
        }

    }
}

SourianaMarket/Controllers/BillItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SourianaMarket.Main.Data.Repositories;
using SourianaMarket.Main.Dto.BillDTO;
using SourianaMarket.Main.IData.Interfaces;
using SourianaMarket.Security;
//using SourianaMarket.Main.Dto.BillItemDTO;
using SourianaMarket.SharedKarnel.Enums;
using SourianaMarket.Util;
using SourianaMarket.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SourianaMarket.Controllers
{
    public class BillItemController : Controller
    {
        public IBillItemInterface BillItemInterface { get; set; }
        public IAccountRepository AccountRepository { get; set; }
        public BillItemController(IBillItemInterface billitemtInterface, IAccountRepository accountRepository)
        {
            BillItemInterface = billitemtInterface;
            AccountRepository = accountRepository;  
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            var userid = AccountRepository.GetUserId();
            var vm = new BillItemViewModel()
            {
                BillItemDto = BillItemInterface.GetAll(userid)

            };
            return View(vm);
        }
        private BillViewModel FillViewModel(BillViewModel model)
        {

            return new BillViewModel()
            {
                BillId = model.BillId,
                ItemId = model.ItemId,
                UserId = model.UserId,
                Quantity = model.Quantity,
                ItemPrice = model.ItemPrice
                //ImageUrl = model.ImageUrl
            };

        }
        public IActionResult RemoveBillItem(int id)
        {

            var userid = AccountRepository.GetUserId();
            bool DelBillItem = BillItemInterface.DeleteBillItem(id, userid);
            if (DelBillItem)
            {
                //return Json("Remove Country successfully");
                return RedirectToAction(nameof(BillItemController.Index), nameof(BillItemController).GetActionName());
            }
            return RedirectToAction(nameof(BillItemController.Index), nameof(BillItemController).GetActionName());
            //Response.StatusCode = (int)HttpStatusCode.BadRequest;
            //return Json("Please retry field to remove country !");
        }
        public IActionResult DeleteAll()
        {
            var userid = AccountRepository.GetUserId();
            bool DeletAllBillItem = BillItemInterface.DeleteAll(userid);
            if (DeletAllBillItem)
            {
                //return Json("Remove Country successfully");
                return RedirectToAction(nameof(BillItemController.Index), nameof(BillItemController).GetActionName());
            }
            return RedirectToAction(nameof(BillItemController.Index), nameof(BillItemController).GetActionName());
        }
        //    [HttpPost]
        //    public IActionResult SaveBillItemInfo(BillViewModel model)
        //    {
        //        string PathDB = string.Empty;

        //        if (!ModelState.IsValid)
        //        {
        //            var viewModel = FillViewModel(model);
        //            ViewBag.error = "Data incorrect";
        //            return RedirectToAction(nameof(CartController.Index), nameof(CartController).GetActionName());
        //        }
        //        var result = BillItemInterface.SetBillItem(new BillDto()
        //        {
        //            BillId = model.BillId,
        //            ItemId = model.ItemId,
        //            Userid = model.UserId,
        //            Quantity = model.Quantity,
        //            ItemPrice = model.ItemPrice
        //        });
        //        if (result.ResultType == OperationResultTypes.Success)
        //        {
        //            //return json(result);
        //            return RedirectToAction(nameof(CartController.Index),
        //                nameof(CartController).GetActionName());
        //        }
        //        ModelState.AddModelError("", "failed to update date");
        //        //var vm = FillViewModel(model);
        //        return RedirectToAction(nameof(CartController.Index),
        //                   nameof(CartController).GetActionName());
        //    }
        //}

        
    }
}

SourianaMarket/Views/BillItem/Index.cshtml
@model BillItemViewModel
 <!-- ****** Cart Area Start ****** -->
<div class="navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="cart_area section_padding_100 clearfix">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="cart-table clearfix">
                        <table class="table table-responsive">
                            <thead>
                                <tr>
                                    <th>Product</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            @foreach (var item in Model.BillItemDto)
                            {
                                <tbody>
                                    <tr>
                                        <td class="cart_product_img d-flex align-items-center">
                                            <a href="#"><img src="@Url.Content(item.ItemImageUrl)" alt="Product"></a>
                                            <h6>@item.ItemName</h6>


                                        </td>
                                        <td class="price"><span>@item.ItemPrice</span></td>
                                        <td class="price"><span>@item.Quantity</span></td>
                                        @*<td class="qty">
                                                <div class="quantity">
                                                    <span class="qty-minus" onclick="var effect = document.getElementById('qty'); var qty = effect.value; if( !isNaN( qty ) &amp;&amp; qty &gt; 1 ) effect.value--;return false;"><i class="fa fa-minus" aria-hidden="true"></i></span>
                                                    <input type="text" class="qty-text" id="qty" step="1" min="1" max="99" name="quantity" value="@item.Quantity">
                                                    <span class="qty-plus" onclick="var effect = document.getElementById('qty'); var qty = effect.value; if( !isNaN( qty )) effect.value++;return false;"><i class="fa fa-plus" aria-hidden="true"></i></span>
                                                </div>
                                            </td>*@
                                        <td class="total_price">@(item.Quantity * item.ItemPrice)<span></span></td>
                                        @*<td> <a href="#">Update</a> </td>*@
                                        <td> <a asp-controller="BillItem" asp-action="RemoveBillItem" asp-route-id="@item.Id">Delete</a> </td>
                                    </tr>

                                </tbody>
                            }
                        </table>
                    </div>

                    <div class="cart-footer d-flex mt-30">
                        <div class="back-to-shop w-50">
                            <a asp-controller="Item" asp-action="Index" asp-route-id="@Model.Categid">Continue shooping</a>
                        </div>
                        <div class="update-checkout w-50 text-right">
                            <a asp-action="DeleteAll" asp-controller="BillItem">clear cart</a>
                            <a asp-action="CheckOut" asp-controller="Bill" >checkout</a>
                        </div>

                    </div>

                </div>
            </div>

            <div class="row">
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="coupon-code-area mt-70">
                        <div class="cart-page-heading">
                            <h5>Cupon code</h5>
                            <p>Enter your cupone code</p>
                        </div>
                        <form action="#">
                            <input type="search" name="search" placeholder="#569ab15">
                            <button type="submit">Apply</button>
                        </form>
                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="shipping-method-area mt-70">
                        <div class="cart-page-heading">
                            <h5>Shipping method</h5>
                            <p>Select the one you want</p>
                        </div>

                        <div class="custom-control custom-radio mb-30">
                            <input type="radio" id="customRadio1" name="customRadio" class="custom-control-input">
                            <label class="custom-control-label d-flex align-items-center justify-content-between" for="customRadio1"><span>Next day delivery</span><span>$4.99</span></label>
                        </div>

                        <div class="custom-control custom-radio mb-30">
                            <input type="radio" id="customRadio2" name="customRadio" class="custom-control-input">
                            <label class="custom-control-label d-flex align-items-center justify-content-between" for="customRadio2"><span>Standard delivery</span><span>$1.99</span></label>
                        </div>

                        <div class="custom-control custom-radio">
                            <input type="radio" id="customRadio3" name="customRadio" class="custom-control-input">
                            <label class="custom-control-label d-flex align-items-center justify-content-between" for="customRadio3"><span>Personal Pickup</span><span>Free</span></label>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-lg-4">
                    <div class="cart-total-area mt-70">
                        <div class="cart-page-heading">
                            <h5>Cart total</h5>
                            <p>Final info</p>
                        </div>

                        <ul class="cart-total-chart">
                            <li><span>Subtotal</span> <span>$59.90</span></li>
                            <li><span>Shipping</span> <span>Free</span></li>
                            <li><span><strong>Total</strong></span> <span><strong>$59.90</strong></span></li>
                        </ul>
                        <a href="checkout.html" class="btn karl-checkout-btn">Proceed to checkout</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- ****** Cart Area End ****** -->
@section Styles {
    <link href="~/ForBrand/css/index.css" rel="stylesheet" />
}